version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: aztv-app
        container_name: aztv-app
        restart: unless-stopped
        volumes:
            - .:/var/www
        depends_on:
            - postgres
        networks:
            - aztv-net

    nginx:
        image: nginx:stable
        container_name: aztv-nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - aztv-net

    postgres:
        image: postgres:15
        container_name: aztv-postgres
        restart: unless-stopped
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: aztv
            POSTGRES_USER: aztv
            POSTGRES_PASSWORD: secret
        networks:
            - aztv-net

networks:
    aztv-net:

volumes:
    pgdata:
